### ISSUE TITLE
Resources In APIs Acts Strangely

### ISSUE THREAD

**Issue by timcortesi** [EscherLabs/GrapheneAPIGateway#19]
When you duplicate a "resource" in 'APIs', the whole thing ends up duplicated (including the word "Resources").  Also, when you instantiate an API, and if you had a resource that you then deleted, you can end up with extra empty resources that are impossible to remove.  (See screenshots)

Talk to Lauri about this.  Because somehow she broke EVERYTHING.

Also this is really a bug in the UI for Graphene, so not really the API Gateway.  

<img width="713" alt="Screen Shot 2019-09-18 at 10 48 11 AM" src="https://user-images.githubusercontent.com/5395437/65159285-d54e1f00-da01-11e9-8f01-9e8ef3127e5d.png">
<img width="610" alt="Screen Shot 2019-09-18 at 10 48 04 AM" src="https://user-images.githubusercontent.com/5395437/65159286-d54e1f00-da01-11e9-9230-144a47236b84.png">

**Comment by Cloverstone** [comment]
first one isn't a bug its just the way duplication works, resources is the label of the duplicated field - we can remove that. The second appears to be a bug.

**Comment by timcortesi** [comment]
This is fixed.
